version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    # We check error as part of our PR process.
    - errcheck

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: true