version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - (golang.org/x/crypto/ssh.Session).WindowChange
        - (golang.org/x/crypto/ssh/terminal).Restore
        - (golang.org/x/crypto/ssh.Client).Close
