[tools]
go = "1.24"
"ubi:golangci/golangci-lint" = "latest"

[env]
CGO_ENABLED=0

[tasks.vendor]
description = "Ensure vendor is up to date"
run = "go mod vendor"

[tasks.test]
description = "Run Go tests with coverage"
run = "go test -cover ./..."
depends = ["vendor"]

[tasks."lint"]
description = "Run Go tests with coverage"
run = "golangci-lint run"
