name: Mise Install

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Mise
        run: |
          curl https://mise.run | sh
          mise install

      - name: Test
        run: |
          mise run test
