name: Mise Install

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - uses: jdx/mise-action@v2
        with:
          version: latest

      - name: Lint
        run: |
          mise run lint
