name: Mise Container

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    container: docker.io/nickschuch/mise:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Lint
        run: |
          mise run test
