name: ☁️ Release

on:
  push:
    tags:
      - '*'

env:
  BUCKET_NAME: package-skpr-io
  AWS_REGION:  us-east-1

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v5

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🔑 Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐋 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ☁️ Release
        run: |
          mise release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release_debs:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: 📁 Make apt repo dirs
        run: mkdir -p apt-repo/pool/main/skpr

      - name: 📦 Download latest release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: skpr/cli
          latest: true
          fileName: "*.deb"
          out-file-path: apt-repo/pool/main/skpr

      - name: ⚙️ Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🔑 Import GPG Private Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: 🔐 List keys
        run: gpg -K

      - name: 📦 Generate Apt Repo
        run: |
          cd apt-repo
          ../scripts/generate-apt-repo.sh
          cd -

      - name: 🔑 Export Public Key
        run: |
          cd apt-repo
          echo "${{ secrets.GPG_PUBLIC_KEY }}" > packages.skpr.io.pub
          cd -

      - name: ☁️ Sync to S3
        run: |
          cd apt-repo
          aws s3 sync --delete . s3://${{ env.BUCKET_NAME }}/apt/
          cd -

      - name: 🧹 Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths /apt/*
